#if !defined(CRADLE_PREPROCESSOR_VA_EAT_HPP_INCLUDE_GUARD)
#define CRADLE_PREPROCESSOR_VA_EAT_HPP_INCLUDE_GUARD


#define CRADLE_PP_VA_EAT(...)


#endif // !defined(CRADLE_PREPROCESSOR_VA_EAT_HPP_INCLUDE_GUARD)
