#if !defined(CRADLE_PREPROCESSOR_VA_FROM_TUPLE_HPP_INCLUDE_GUARD)
#define CRADLE_PREPROCESSOR_VA_FROM_TUPLE_HPP_INCLUDE_GUARD

#include <boost/preprocessor/facilities/expand.hpp>


#define CRADLE_PP_VA_FROM_TUPLE_IMPL(...) __VA_ARGS__

#define CRADLE_PP_VA_FROM_TUPLE(TUPLE) CRADLE_PP_VA_FROM_TUPLE_IMPL TUPLE
  /**/


#endif // !defined(CRADLE_PREPROCESSOR_VA_FROM_TUPLE_HPP_INCLUDE_GUARD)
