#if !defined(CRADLE_PREPROCESSOR_CONFIG_HPP_INCLUDE_GUARD)
#define CRADLE_PREPROCESSOR_CONFIG_HPP_INCLUDE_GUARD


#define CRADLE_PP_LIMIT_VA 25


#endif // !defined(CRADLE_PREPROCESSOR_CONFIG_HPP_INCLUDE_GUARD)
