#if !defined(CRADLE_PREPROCESSOR_INVOKE_HPP_INCLUDE_GUARD)
#define CRADLE_PREPROCESSOR_INVOKE_HPP_INCLUDE_GUARD

#include <boost/preprocessor/detail/auto_rec.hpp>
#include <boost/preprocessor/cat.hpp>


#define CRADLE_PP_INVOKE                                                    \
BOOST_PP_CAT(CRADLE_PP_INVOKE_, BOOST_PP_AUTO_REC(CRADLE_PP_INVOKE_P, 256)) \
/////////////////////////////////////////////////////////////////////////////

#define CRADLE_PP_INVOKE_P(N)                                               \
BOOST_PP_CAT(                                                               \
  CRADLE_PP_INVOKE_CHECK_,                                                  \
  CRADLE_PP_INVOKE_ ## N(CRADLE_PP_INVOKE_NIL CRADLE_PP_INVOKE_TUPLE_EAT_1, \
                         CRADLE_PP_INVOKE_NIL))                             \
/////////////////////////////////////////////////////////////////////////////

#define CRADLE_PP_INVOKE_TUPLE_EAT_1(P)

#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_NIL 1
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_1(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_2(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_3(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_4(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_5(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_6(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_7(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_8(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_9(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_10(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_11(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_12(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_13(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_14(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_15(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_16(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_17(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_18(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_19(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_20(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_21(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_22(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_23(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_24(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_25(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_26(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_27(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_28(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_29(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_30(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_31(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_32(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_33(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_34(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_35(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_36(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_37(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_38(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_39(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_40(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_41(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_42(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_43(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_44(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_45(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_46(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_47(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_48(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_49(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_50(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_51(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_52(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_53(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_54(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_55(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_56(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_57(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_58(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_59(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_60(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_61(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_62(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_63(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_64(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_65(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_66(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_67(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_68(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_69(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_70(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_71(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_72(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_73(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_74(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_75(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_76(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_77(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_78(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_79(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_80(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_81(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_82(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_83(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_84(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_85(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_86(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_87(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_88(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_89(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_90(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_91(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_92(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_93(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_94(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_95(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_96(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_97(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_98(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_99(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_100(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_101(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_102(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_103(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_104(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_105(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_106(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_107(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_108(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_109(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_110(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_111(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_112(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_113(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_114(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_115(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_116(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_117(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_118(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_119(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_120(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_121(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_122(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_123(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_124(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_125(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_126(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_127(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_128(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_129(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_130(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_131(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_132(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_133(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_134(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_135(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_136(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_137(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_138(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_139(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_140(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_141(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_142(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_143(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_144(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_145(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_146(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_147(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_148(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_149(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_150(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_151(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_152(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_153(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_154(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_155(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_156(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_157(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_158(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_159(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_160(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_161(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_162(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_163(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_164(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_165(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_166(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_167(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_168(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_169(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_170(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_171(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_172(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_173(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_174(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_175(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_176(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_177(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_178(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_179(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_180(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_181(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_182(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_183(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_184(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_185(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_186(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_187(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_188(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_189(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_190(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_191(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_192(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_193(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_194(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_195(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_196(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_197(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_198(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_199(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_200(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_201(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_202(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_203(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_204(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_205(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_206(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_207(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_208(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_209(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_210(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_211(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_212(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_213(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_214(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_215(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_216(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_217(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_218(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_219(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_220(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_221(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_222(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_223(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_224(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_225(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_226(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_227(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_228(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_229(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_230(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_231(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_232(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_233(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_234(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_235(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_236(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_237(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_238(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_239(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_240(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_241(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_242(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_243(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_244(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_245(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_246(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_247(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_248(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_249(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_250(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_251(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_252(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_253(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_254(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_255(MACRO, ...) 0
#define CRADLE_PP_INVOKE_CHECK_CRADLE_PP_INVOKE_256(MACRO, ...) 0

#define CRADLE_PP_INVOKE_1(MACRO, ...) CRADLE_PP_INVOKE_IMPL_1(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_2(MACRO, ...) CRADLE_PP_INVOKE_IMPL_2(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_3(MACRO, ...) CRADLE_PP_INVOKE_IMPL_3(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_4(MACRO, ...) CRADLE_PP_INVOKE_IMPL_4(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_5(MACRO, ...) CRADLE_PP_INVOKE_IMPL_5(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_6(MACRO, ...) CRADLE_PP_INVOKE_IMPL_6(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_7(MACRO, ...) CRADLE_PP_INVOKE_IMPL_7(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_8(MACRO, ...) CRADLE_PP_INVOKE_IMPL_8(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_9(MACRO, ...) CRADLE_PP_INVOKE_IMPL_9(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_10(MACRO, ...) CRADLE_PP_INVOKE_IMPL_10(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_11(MACRO, ...) CRADLE_PP_INVOKE_IMPL_11(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_12(MACRO, ...) CRADLE_PP_INVOKE_IMPL_12(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_13(MACRO, ...) CRADLE_PP_INVOKE_IMPL_13(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_14(MACRO, ...) CRADLE_PP_INVOKE_IMPL_14(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_15(MACRO, ...) CRADLE_PP_INVOKE_IMPL_15(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_16(MACRO, ...) CRADLE_PP_INVOKE_IMPL_16(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_17(MACRO, ...) CRADLE_PP_INVOKE_IMPL_17(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_18(MACRO, ...) CRADLE_PP_INVOKE_IMPL_18(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_19(MACRO, ...) CRADLE_PP_INVOKE_IMPL_19(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_20(MACRO, ...) CRADLE_PP_INVOKE_IMPL_20(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_21(MACRO, ...) CRADLE_PP_INVOKE_IMPL_21(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_22(MACRO, ...) CRADLE_PP_INVOKE_IMPL_22(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_23(MACRO, ...) CRADLE_PP_INVOKE_IMPL_23(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_24(MACRO, ...) CRADLE_PP_INVOKE_IMPL_24(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_25(MACRO, ...) CRADLE_PP_INVOKE_IMPL_25(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_26(MACRO, ...) CRADLE_PP_INVOKE_IMPL_26(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_27(MACRO, ...) CRADLE_PP_INVOKE_IMPL_27(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_28(MACRO, ...) CRADLE_PP_INVOKE_IMPL_28(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_29(MACRO, ...) CRADLE_PP_INVOKE_IMPL_29(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_30(MACRO, ...) CRADLE_PP_INVOKE_IMPL_30(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_31(MACRO, ...) CRADLE_PP_INVOKE_IMPL_31(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_32(MACRO, ...) CRADLE_PP_INVOKE_IMPL_32(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_33(MACRO, ...) CRADLE_PP_INVOKE_IMPL_33(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_34(MACRO, ...) CRADLE_PP_INVOKE_IMPL_34(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_35(MACRO, ...) CRADLE_PP_INVOKE_IMPL_35(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_36(MACRO, ...) CRADLE_PP_INVOKE_IMPL_36(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_37(MACRO, ...) CRADLE_PP_INVOKE_IMPL_37(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_38(MACRO, ...) CRADLE_PP_INVOKE_IMPL_38(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_39(MACRO, ...) CRADLE_PP_INVOKE_IMPL_39(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_40(MACRO, ...) CRADLE_PP_INVOKE_IMPL_40(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_41(MACRO, ...) CRADLE_PP_INVOKE_IMPL_41(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_42(MACRO, ...) CRADLE_PP_INVOKE_IMPL_42(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_43(MACRO, ...) CRADLE_PP_INVOKE_IMPL_43(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_44(MACRO, ...) CRADLE_PP_INVOKE_IMPL_44(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_45(MACRO, ...) CRADLE_PP_INVOKE_IMPL_45(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_46(MACRO, ...) CRADLE_PP_INVOKE_IMPL_46(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_47(MACRO, ...) CRADLE_PP_INVOKE_IMPL_47(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_48(MACRO, ...) CRADLE_PP_INVOKE_IMPL_48(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_49(MACRO, ...) CRADLE_PP_INVOKE_IMPL_49(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_50(MACRO, ...) CRADLE_PP_INVOKE_IMPL_50(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_51(MACRO, ...) CRADLE_PP_INVOKE_IMPL_51(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_52(MACRO, ...) CRADLE_PP_INVOKE_IMPL_52(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_53(MACRO, ...) CRADLE_PP_INVOKE_IMPL_53(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_54(MACRO, ...) CRADLE_PP_INVOKE_IMPL_54(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_55(MACRO, ...) CRADLE_PP_INVOKE_IMPL_55(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_56(MACRO, ...) CRADLE_PP_INVOKE_IMPL_56(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_57(MACRO, ...) CRADLE_PP_INVOKE_IMPL_57(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_58(MACRO, ...) CRADLE_PP_INVOKE_IMPL_58(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_59(MACRO, ...) CRADLE_PP_INVOKE_IMPL_59(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_60(MACRO, ...) CRADLE_PP_INVOKE_IMPL_60(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_61(MACRO, ...) CRADLE_PP_INVOKE_IMPL_61(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_62(MACRO, ...) CRADLE_PP_INVOKE_IMPL_62(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_63(MACRO, ...) CRADLE_PP_INVOKE_IMPL_63(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_64(MACRO, ...) CRADLE_PP_INVOKE_IMPL_64(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_65(MACRO, ...) CRADLE_PP_INVOKE_IMPL_65(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_66(MACRO, ...) CRADLE_PP_INVOKE_IMPL_66(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_67(MACRO, ...) CRADLE_PP_INVOKE_IMPL_67(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_68(MACRO, ...) CRADLE_PP_INVOKE_IMPL_68(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_69(MACRO, ...) CRADLE_PP_INVOKE_IMPL_69(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_70(MACRO, ...) CRADLE_PP_INVOKE_IMPL_70(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_71(MACRO, ...) CRADLE_PP_INVOKE_IMPL_71(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_72(MACRO, ...) CRADLE_PP_INVOKE_IMPL_72(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_73(MACRO, ...) CRADLE_PP_INVOKE_IMPL_73(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_74(MACRO, ...) CRADLE_PP_INVOKE_IMPL_74(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_75(MACRO, ...) CRADLE_PP_INVOKE_IMPL_75(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_76(MACRO, ...) CRADLE_PP_INVOKE_IMPL_76(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_77(MACRO, ...) CRADLE_PP_INVOKE_IMPL_77(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_78(MACRO, ...) CRADLE_PP_INVOKE_IMPL_78(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_79(MACRO, ...) CRADLE_PP_INVOKE_IMPL_79(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_80(MACRO, ...) CRADLE_PP_INVOKE_IMPL_80(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_81(MACRO, ...) CRADLE_PP_INVOKE_IMPL_81(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_82(MACRO, ...) CRADLE_PP_INVOKE_IMPL_82(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_83(MACRO, ...) CRADLE_PP_INVOKE_IMPL_83(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_84(MACRO, ...) CRADLE_PP_INVOKE_IMPL_84(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_85(MACRO, ...) CRADLE_PP_INVOKE_IMPL_85(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_86(MACRO, ...) CRADLE_PP_INVOKE_IMPL_86(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_87(MACRO, ...) CRADLE_PP_INVOKE_IMPL_87(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_88(MACRO, ...) CRADLE_PP_INVOKE_IMPL_88(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_89(MACRO, ...) CRADLE_PP_INVOKE_IMPL_89(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_90(MACRO, ...) CRADLE_PP_INVOKE_IMPL_90(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_91(MACRO, ...) CRADLE_PP_INVOKE_IMPL_91(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_92(MACRO, ...) CRADLE_PP_INVOKE_IMPL_92(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_93(MACRO, ...) CRADLE_PP_INVOKE_IMPL_93(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_94(MACRO, ...) CRADLE_PP_INVOKE_IMPL_94(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_95(MACRO, ...) CRADLE_PP_INVOKE_IMPL_95(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_96(MACRO, ...) CRADLE_PP_INVOKE_IMPL_96(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_97(MACRO, ...) CRADLE_PP_INVOKE_IMPL_97(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_98(MACRO, ...) CRADLE_PP_INVOKE_IMPL_98(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_99(MACRO, ...) CRADLE_PP_INVOKE_IMPL_99(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_100(MACRO, ...) CRADLE_PP_INVOKE_IMPL_100(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_101(MACRO, ...) CRADLE_PP_INVOKE_IMPL_101(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_102(MACRO, ...) CRADLE_PP_INVOKE_IMPL_102(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_103(MACRO, ...) CRADLE_PP_INVOKE_IMPL_103(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_104(MACRO, ...) CRADLE_PP_INVOKE_IMPL_104(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_105(MACRO, ...) CRADLE_PP_INVOKE_IMPL_105(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_106(MACRO, ...) CRADLE_PP_INVOKE_IMPL_106(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_107(MACRO, ...) CRADLE_PP_INVOKE_IMPL_107(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_108(MACRO, ...) CRADLE_PP_INVOKE_IMPL_108(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_109(MACRO, ...) CRADLE_PP_INVOKE_IMPL_109(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_110(MACRO, ...) CRADLE_PP_INVOKE_IMPL_110(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_111(MACRO, ...) CRADLE_PP_INVOKE_IMPL_111(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_112(MACRO, ...) CRADLE_PP_INVOKE_IMPL_112(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_113(MACRO, ...) CRADLE_PP_INVOKE_IMPL_113(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_114(MACRO, ...) CRADLE_PP_INVOKE_IMPL_114(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_115(MACRO, ...) CRADLE_PP_INVOKE_IMPL_115(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_116(MACRO, ...) CRADLE_PP_INVOKE_IMPL_116(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_117(MACRO, ...) CRADLE_PP_INVOKE_IMPL_117(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_118(MACRO, ...) CRADLE_PP_INVOKE_IMPL_118(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_119(MACRO, ...) CRADLE_PP_INVOKE_IMPL_119(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_120(MACRO, ...) CRADLE_PP_INVOKE_IMPL_120(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_121(MACRO, ...) CRADLE_PP_INVOKE_IMPL_121(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_122(MACRO, ...) CRADLE_PP_INVOKE_IMPL_122(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_123(MACRO, ...) CRADLE_PP_INVOKE_IMPL_123(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_124(MACRO, ...) CRADLE_PP_INVOKE_IMPL_124(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_125(MACRO, ...) CRADLE_PP_INVOKE_IMPL_125(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_126(MACRO, ...) CRADLE_PP_INVOKE_IMPL_126(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_127(MACRO, ...) CRADLE_PP_INVOKE_IMPL_127(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_128(MACRO, ...) CRADLE_PP_INVOKE_IMPL_128(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_129(MACRO, ...) CRADLE_PP_INVOKE_IMPL_129(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_130(MACRO, ...) CRADLE_PP_INVOKE_IMPL_130(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_131(MACRO, ...) CRADLE_PP_INVOKE_IMPL_131(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_132(MACRO, ...) CRADLE_PP_INVOKE_IMPL_132(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_133(MACRO, ...) CRADLE_PP_INVOKE_IMPL_133(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_134(MACRO, ...) CRADLE_PP_INVOKE_IMPL_134(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_135(MACRO, ...) CRADLE_PP_INVOKE_IMPL_135(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_136(MACRO, ...) CRADLE_PP_INVOKE_IMPL_136(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_137(MACRO, ...) CRADLE_PP_INVOKE_IMPL_137(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_138(MACRO, ...) CRADLE_PP_INVOKE_IMPL_138(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_139(MACRO, ...) CRADLE_PP_INVOKE_IMPL_139(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_140(MACRO, ...) CRADLE_PP_INVOKE_IMPL_140(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_141(MACRO, ...) CRADLE_PP_INVOKE_IMPL_141(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_142(MACRO, ...) CRADLE_PP_INVOKE_IMPL_142(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_143(MACRO, ...) CRADLE_PP_INVOKE_IMPL_143(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_144(MACRO, ...) CRADLE_PP_INVOKE_IMPL_144(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_145(MACRO, ...) CRADLE_PP_INVOKE_IMPL_145(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_146(MACRO, ...) CRADLE_PP_INVOKE_IMPL_146(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_147(MACRO, ...) CRADLE_PP_INVOKE_IMPL_147(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_148(MACRO, ...) CRADLE_PP_INVOKE_IMPL_148(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_149(MACRO, ...) CRADLE_PP_INVOKE_IMPL_149(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_150(MACRO, ...) CRADLE_PP_INVOKE_IMPL_150(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_151(MACRO, ...) CRADLE_PP_INVOKE_IMPL_151(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_152(MACRO, ...) CRADLE_PP_INVOKE_IMPL_152(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_153(MACRO, ...) CRADLE_PP_INVOKE_IMPL_153(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_154(MACRO, ...) CRADLE_PP_INVOKE_IMPL_154(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_155(MACRO, ...) CRADLE_PP_INVOKE_IMPL_155(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_156(MACRO, ...) CRADLE_PP_INVOKE_IMPL_156(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_157(MACRO, ...) CRADLE_PP_INVOKE_IMPL_157(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_158(MACRO, ...) CRADLE_PP_INVOKE_IMPL_158(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_159(MACRO, ...) CRADLE_PP_INVOKE_IMPL_159(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_160(MACRO, ...) CRADLE_PP_INVOKE_IMPL_160(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_161(MACRO, ...) CRADLE_PP_INVOKE_IMPL_161(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_162(MACRO, ...) CRADLE_PP_INVOKE_IMPL_162(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_163(MACRO, ...) CRADLE_PP_INVOKE_IMPL_163(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_164(MACRO, ...) CRADLE_PP_INVOKE_IMPL_164(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_165(MACRO, ...) CRADLE_PP_INVOKE_IMPL_165(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_166(MACRO, ...) CRADLE_PP_INVOKE_IMPL_166(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_167(MACRO, ...) CRADLE_PP_INVOKE_IMPL_167(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_168(MACRO, ...) CRADLE_PP_INVOKE_IMPL_168(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_169(MACRO, ...) CRADLE_PP_INVOKE_IMPL_169(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_170(MACRO, ...) CRADLE_PP_INVOKE_IMPL_170(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_171(MACRO, ...) CRADLE_PP_INVOKE_IMPL_171(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_172(MACRO, ...) CRADLE_PP_INVOKE_IMPL_172(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_173(MACRO, ...) CRADLE_PP_INVOKE_IMPL_173(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_174(MACRO, ...) CRADLE_PP_INVOKE_IMPL_174(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_175(MACRO, ...) CRADLE_PP_INVOKE_IMPL_175(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_176(MACRO, ...) CRADLE_PP_INVOKE_IMPL_176(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_177(MACRO, ...) CRADLE_PP_INVOKE_IMPL_177(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_178(MACRO, ...) CRADLE_PP_INVOKE_IMPL_178(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_179(MACRO, ...) CRADLE_PP_INVOKE_IMPL_179(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_180(MACRO, ...) CRADLE_PP_INVOKE_IMPL_180(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_181(MACRO, ...) CRADLE_PP_INVOKE_IMPL_181(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_182(MACRO, ...) CRADLE_PP_INVOKE_IMPL_182(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_183(MACRO, ...) CRADLE_PP_INVOKE_IMPL_183(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_184(MACRO, ...) CRADLE_PP_INVOKE_IMPL_184(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_185(MACRO, ...) CRADLE_PP_INVOKE_IMPL_185(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_186(MACRO, ...) CRADLE_PP_INVOKE_IMPL_186(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_187(MACRO, ...) CRADLE_PP_INVOKE_IMPL_187(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_188(MACRO, ...) CRADLE_PP_INVOKE_IMPL_188(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_189(MACRO, ...) CRADLE_PP_INVOKE_IMPL_189(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_190(MACRO, ...) CRADLE_PP_INVOKE_IMPL_190(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_191(MACRO, ...) CRADLE_PP_INVOKE_IMPL_191(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_192(MACRO, ...) CRADLE_PP_INVOKE_IMPL_192(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_193(MACRO, ...) CRADLE_PP_INVOKE_IMPL_193(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_194(MACRO, ...) CRADLE_PP_INVOKE_IMPL_194(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_195(MACRO, ...) CRADLE_PP_INVOKE_IMPL_195(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_196(MACRO, ...) CRADLE_PP_INVOKE_IMPL_196(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_197(MACRO, ...) CRADLE_PP_INVOKE_IMPL_197(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_198(MACRO, ...) CRADLE_PP_INVOKE_IMPL_198(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_199(MACRO, ...) CRADLE_PP_INVOKE_IMPL_199(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_200(MACRO, ...) CRADLE_PP_INVOKE_IMPL_200(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_201(MACRO, ...) CRADLE_PP_INVOKE_IMPL_201(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_202(MACRO, ...) CRADLE_PP_INVOKE_IMPL_202(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_203(MACRO, ...) CRADLE_PP_INVOKE_IMPL_203(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_204(MACRO, ...) CRADLE_PP_INVOKE_IMPL_204(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_205(MACRO, ...) CRADLE_PP_INVOKE_IMPL_205(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_206(MACRO, ...) CRADLE_PP_INVOKE_IMPL_206(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_207(MACRO, ...) CRADLE_PP_INVOKE_IMPL_207(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_208(MACRO, ...) CRADLE_PP_INVOKE_IMPL_208(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_209(MACRO, ...) CRADLE_PP_INVOKE_IMPL_209(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_210(MACRO, ...) CRADLE_PP_INVOKE_IMPL_210(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_211(MACRO, ...) CRADLE_PP_INVOKE_IMPL_211(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_212(MACRO, ...) CRADLE_PP_INVOKE_IMPL_212(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_213(MACRO, ...) CRADLE_PP_INVOKE_IMPL_213(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_214(MACRO, ...) CRADLE_PP_INVOKE_IMPL_214(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_215(MACRO, ...) CRADLE_PP_INVOKE_IMPL_215(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_216(MACRO, ...) CRADLE_PP_INVOKE_IMPL_216(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_217(MACRO, ...) CRADLE_PP_INVOKE_IMPL_217(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_218(MACRO, ...) CRADLE_PP_INVOKE_IMPL_218(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_219(MACRO, ...) CRADLE_PP_INVOKE_IMPL_219(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_220(MACRO, ...) CRADLE_PP_INVOKE_IMPL_220(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_221(MACRO, ...) CRADLE_PP_INVOKE_IMPL_221(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_222(MACRO, ...) CRADLE_PP_INVOKE_IMPL_222(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_223(MACRO, ...) CRADLE_PP_INVOKE_IMPL_223(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_224(MACRO, ...) CRADLE_PP_INVOKE_IMPL_224(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_225(MACRO, ...) CRADLE_PP_INVOKE_IMPL_225(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_226(MACRO, ...) CRADLE_PP_INVOKE_IMPL_226(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_227(MACRO, ...) CRADLE_PP_INVOKE_IMPL_227(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_228(MACRO, ...) CRADLE_PP_INVOKE_IMPL_228(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_229(MACRO, ...) CRADLE_PP_INVOKE_IMPL_229(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_230(MACRO, ...) CRADLE_PP_INVOKE_IMPL_230(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_231(MACRO, ...) CRADLE_PP_INVOKE_IMPL_231(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_232(MACRO, ...) CRADLE_PP_INVOKE_IMPL_232(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_233(MACRO, ...) CRADLE_PP_INVOKE_IMPL_233(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_234(MACRO, ...) CRADLE_PP_INVOKE_IMPL_234(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_235(MACRO, ...) CRADLE_PP_INVOKE_IMPL_235(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_236(MACRO, ...) CRADLE_PP_INVOKE_IMPL_236(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_237(MACRO, ...) CRADLE_PP_INVOKE_IMPL_237(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_238(MACRO, ...) CRADLE_PP_INVOKE_IMPL_238(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_239(MACRO, ...) CRADLE_PP_INVOKE_IMPL_239(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_240(MACRO, ...) CRADLE_PP_INVOKE_IMPL_240(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_241(MACRO, ...) CRADLE_PP_INVOKE_IMPL_241(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_242(MACRO, ...) CRADLE_PP_INVOKE_IMPL_242(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_243(MACRO, ...) CRADLE_PP_INVOKE_IMPL_243(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_244(MACRO, ...) CRADLE_PP_INVOKE_IMPL_244(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_245(MACRO, ...) CRADLE_PP_INVOKE_IMPL_245(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_246(MACRO, ...) CRADLE_PP_INVOKE_IMPL_246(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_247(MACRO, ...) CRADLE_PP_INVOKE_IMPL_247(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_248(MACRO, ...) CRADLE_PP_INVOKE_IMPL_248(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_249(MACRO, ...) CRADLE_PP_INVOKE_IMPL_249(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_250(MACRO, ...) CRADLE_PP_INVOKE_IMPL_250(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_251(MACRO, ...) CRADLE_PP_INVOKE_IMPL_251(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_252(MACRO, ...) CRADLE_PP_INVOKE_IMPL_252(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_253(MACRO, ...) CRADLE_PP_INVOKE_IMPL_253(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_254(MACRO, ...) CRADLE_PP_INVOKE_IMPL_254(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_255(MACRO, ...) CRADLE_PP_INVOKE_IMPL_255(MACRO, (__VA_ARGS__))
#define CRADLE_PP_INVOKE_256(MACRO, ...) CRADLE_PP_INVOKE_IMPL_256(MACRO, (__VA_ARGS__))

#define CRADLE_PP_INVOKE_IMPL_1(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_2(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_3(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_4(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_5(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_6(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_7(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_8(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_9(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_10(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_11(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_12(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_13(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_14(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_15(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_16(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_17(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_18(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_19(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_20(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_21(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_22(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_23(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_24(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_25(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_26(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_27(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_28(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_29(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_30(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_31(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_32(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_33(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_34(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_35(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_36(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_37(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_38(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_39(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_40(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_41(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_42(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_43(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_44(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_45(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_46(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_47(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_48(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_49(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_50(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_51(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_52(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_53(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_54(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_55(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_56(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_57(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_58(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_59(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_60(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_61(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_62(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_63(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_64(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_65(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_66(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_67(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_68(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_69(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_70(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_71(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_72(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_73(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_74(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_75(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_76(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_77(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_78(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_79(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_80(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_81(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_82(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_83(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_84(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_85(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_86(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_87(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_88(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_89(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_90(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_91(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_92(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_93(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_94(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_95(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_96(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_97(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_98(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_99(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_100(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_101(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_102(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_103(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_104(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_105(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_106(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_107(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_108(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_109(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_110(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_111(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_112(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_113(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_114(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_115(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_116(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_117(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_118(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_119(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_120(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_121(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_122(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_123(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_124(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_125(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_126(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_127(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_128(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_129(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_130(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_131(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_132(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_133(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_134(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_135(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_136(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_137(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_138(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_139(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_140(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_141(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_142(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_143(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_144(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_145(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_146(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_147(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_148(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_149(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_150(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_151(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_152(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_153(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_154(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_155(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_156(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_157(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_158(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_159(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_160(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_161(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_162(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_163(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_164(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_165(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_166(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_167(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_168(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_169(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_170(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_171(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_172(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_173(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_174(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_175(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_176(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_177(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_178(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_179(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_180(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_181(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_182(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_183(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_184(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_185(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_186(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_187(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_188(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_189(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_190(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_191(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_192(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_193(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_194(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_195(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_196(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_197(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_198(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_199(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_200(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_201(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_202(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_203(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_204(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_205(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_206(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_207(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_208(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_209(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_210(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_211(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_212(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_213(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_214(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_215(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_216(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_217(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_218(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_219(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_220(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_221(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_222(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_223(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_224(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_225(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_226(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_227(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_228(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_229(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_230(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_231(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_232(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_233(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_234(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_235(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_236(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_237(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_238(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_239(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_240(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_241(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_242(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_243(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_244(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_245(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_246(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_247(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_248(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_249(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_250(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_251(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_252(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_253(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_254(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_255(MACRO, VA_TUPLE) MACRO VA_TUPLE
#define CRADLE_PP_INVOKE_IMPL_256(MACRO, VA_TUPLE) MACRO VA_TUPLE


#endif // !defined(CRADLE_PREPROCESSOR_INVOKE_HPP_INCLUDE_GUARD)
